### PR TITLE
Update mime_type_link_images.php

### PR DESCRIPTION
**Pull request by birgire**
Added the priority of 15 to pause_mtli() and unpause_mtli() functions, to match the initial add_filter setup.

### CODE REVIEW

**Comment by jrfnl** [comment]
Looks good to me!

**Comment by birgire** [comment]
Great, any plans of merging this into the current version?

**Comment by jrfnl** [comment]
I would if I had push access ;-) /cc @eagerterrier

**Comment by eagerterrier** [comment]
ha! sorry - haven’t had time to give it a once over, but if it’s good enough for Juliette, it’s good enough for me

I’ll try and push, then send to WP later this week

**Comment by birgire** [comment]
That would be great, looking forward to it ;-)

**Pull request merged**
